feat(GCE): Add docs describing image deletion and deprecation
canonical/ubuntu-cloud-docs pull request #126
Opened 2023-12-11 02:47 UTC by kajiya3141

We have recently implemented a deletion policy, which is a change from the norm where all images were just stored. This commit details where we will start deleting old images and gives a brief decription of deprecation as well.

2023-12-11 09:34 UTC, k-dimple requested changes
Since this fits in better as an explanation rather than a how-to guide, could you move the file to the explanations folder? Also, I have added some minor comments about the styling that we use. Thanks! :)

2023-12-11 09:34 UTC, k-dimple commented on google/google-how-to/gce/gce-image-retention-policy.rst
> +GCE Ubuntu Image Deletion
sentence case

2023-12-11 09:34 UTC, k-dimple commented on google/google-how-to/gce/gce-image-retention-policy.rst
> +Release images are tested and therefore benefit from Canonical's in-life support. Please see how to list both "daily" and "release" images here: :doc:`find-ubuntu-images`.
We usually avoid using the word 'please' in documentation ..

2023-12-11 09:34 UTC, k-dimple commented on google/google-how-to/gce/gce-image-retention-policy.rst
> +As of late 2023, older daily and release images are subject to a retention policy. The policy can be summarised as follows:
Let's not put in a date, as it seems to imply that we won't be keeping our docs current. It is a safer and more accurate statement, but it won't build trust. So we'll just have try to ensure that we make relevant changes to this doc whenever the retention policy changes the next time.

2023-12-11 09:34 UTC, k-dimple commented on google/google-how-to/gce/gce-image-retention-policy.rst
> +  │                 │ EOL*   │ Delete all *but* the lastest serial  │ Delete all *but* the latest serial │
typo: lastest -> latest

2023-12-11 09:34 UTC, k-dimple commented on google/google-how-to/gce/gce-image-retention-policy.rst
> +  │                 │ EOSS** │ Delete all *but* the lastest serial  │ No images are deleted              │
typo: lastest -> latest

2023-12-11 09:34 UTC, k-dimple commented on google/google-how-to/gce/gce-image-retention-policy.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~
sentence case and longer underline

2023-12-11 09:34 UTC, k-dimple commented on google/google-how-to/gce/index.rst
> +   gce-image-retention-policy
Since this is an explanation and not a how-to guide, remove this entry from here and add it to the index.rst in the google-explanation folder

2023-12-13 11:42 UTC, k-dimple approved these changes
The link to 'find-ubuntu-images' had to be corrected since you moved this file. I have made the change and directly committed it to your branch. Hope that's okay. I'll merge it now, thanks!

2023-12-13 11:42 UTC, merged

2023-12-13 15:18 UTC, kajiya3141 commented
> The link to 'find-ubuntu-images' had to be corrected since you moved this file. I have made the change and directly committed it to your branch. Hope that's okay. I'll merge it now, thanks!

Of course! Thanks Dimple :smile: