[AWS] Document EKS snap and its updates
canonical/ubuntu-cloud-docs pull request #152
Opened 2024-01-23 14:14 UTC by woky

2024-01-23 14:22 UTC, toabctl commented on aws/aws-explanation/eks-kubelet-snap.rst
> +    sudo snap refresh --unhold
nit: maybe add a note that this unholds everything? including `kubectl` and `aws-cli` ?

2024-01-23 14:24 UTC, rpocase requested changes
open to wording on requests

2024-01-23 14:24 UTC, rpocase commented on aws/aws-explanation/eks-kubelet-snap.rst
> +Updates of kubelet-eks snap shouldn't affect running workloads.
```suggestion
Updates of kubelet-eks snap shouldn't affect running workloads, but kubeapi access for the node is expected to be unavailable for up to 30 seconds.
```

2024-01-23 14:37 UTC, woky commented on aws/aws-explanation/eks-kubelet-snap.rst
> +Updates of kubelet-eks snap shouldn't affect running workloads.
I've replaced kubeapi with _ Kubernetes API_.

2024-01-24 05:51 UTC, k-dimple approved these changes
This looks good. Is it okay if I put it under the 'reference' section instead of 'explanation'? It seems to contain information that is more appropriate for 'work' rather than 'study'.

2024-01-24 05:51 UTC, merged

2024-01-24 08:43 UTC, woky commented
@k-dimple Sounds good to me.