All references to an Ubuntu LTS version should include 'LTS'
canonical/ubuntu-cloud-docs pull request #243
Opened 2024-06-07 17:53 UTC by k-dimple

2024-06-07 18:00 UTC, danpdraper requested changes
Who is calling for these changes? Marketing?

2024-06-07 18:14 UTC, k-dimple commented on aws/aws-how-to/kubernetes/deploy-ubuntu-pro-cluster.rst
> +Although Ubuntu Pro for EKS is available as an AMI for Ubuntu 22.04 LTS, (see :doc:`deploy-ubuntu-pro-cluster-with-eks-pro-ami`), there is no such EKS related offer available for Ubuntu 20.04 LTS.
Thanks for the catch! I have removed it.

2024-06-07 18:15 UTC, k-dimple commented
> Who is calling for these changes? Marketing?

It's in our [branding guidelines](https://docs.ubuntu.com/styleguide/en#branding) which are framed based on inputs from Marketing.

2024-06-10 07:59 UTC, gjolly approved these changes
I like consistency!

2024-06-10 12:38 UTC, utkarsh2102 approved these changes

2024-06-10 18:19 UTC, danpdraper approved these changes

2024-06-10 19:26 UTC, merged