docs: add section on local cloud-init dataource
canonical/ubuntu-cloud-docs pull request #260
Opened 2024-08-06 20:25 UTC by codyshepherd

Refs:
- https://warthogs.atlassian.net/browse/CPC-4698

2024-08-07 14:00 UTC, j5awry commented
holy sphinx upstream issues batman!

```
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

not sure if this is going to cause failures to build generally

2024-08-07 14:38 UTC, k-dimple commented
Yeah, it is causing general build failures for our code. I am looking into it. (We can avoid the error if we decide to remove all images from our code! :) .. but we are not going to do that)

2024-08-12 14:27 UTC, k-dimple requested changes

2024-08-12 14:27 UTC, k-dimple commented on public-images/public-images-how-to/index.rst
> +- :ref:`use-local-ds`
At the end of this file (under the section toctree section) add: 
`Use a local cloud-init datasource <use-local-ds>`

2024-08-12 14:27 UTC, k-dimple commented on public-images/public-images-how-to/use-local-cloud-init-ds.rst
> +Create and Use a Local Cloud-Init Datasource
```suggestion
Create and use a local cloud-init datasource
```

2024-08-12 14:27 UTC, k-dimple commented on public-images/public-images-how-to/use-local-cloud-init-ds.rst
> +The steps in this How-To guide will allow you to create a seed image that defines a custom cloud-init datasource.
```suggestion
The steps in this how-to guide will allow you to create an Ubuntu seed image that defines a custom cloud-init datasource.
```
Does the above suggestion make sense? When you say seed image, I usually assume something like a core Ubuntu image that can be used as the starting point for adding further packages or making changes that customise it.

2024-08-12 14:27 UTC, k-dimple commented on public-images/public-images-how-to/use-local-cloud-init-ds.rst
> +
Can we add one more line here about why one might want to do this, i.e. launch such customised images locally? Is it for some sort of testing?

2024-08-12 14:27 UTC, k-dimple commented on public-images/public-images-how-to/use-local-cloud-init-ds.rst
> +Datasource metadata (optional)
```suggestion
Specify datasource metadata (optional)
```

2024-08-12 15:11 UTC, codyshepherd commented on public-images/public-images-how-to/use-local-cloud-init-ds.rst
> +If desired, create a YAML file with your desired datasource `metadata`_. Metadata describes typically cloud-defined
I disagree with this suggestion. The metadata is typically cloud-defined (except in cases like this when there's not an actual cloud). Metadata _always_ describes this data.

2024-08-12 15:15 UTC, codyshepherd commented on public-images/public-images-how-to/use-local-cloud-init-ds.rst
> +* virtio network device that redirects guest port 22 to host's port 2222
That's correct. This is pretty standard terminology in the context of virtualization/containerization. I'll add a bit of extra text.

2024-08-12 15:20 UTC, codyshepherd commented on public-images/public-images-how-to/use-local-cloud-init-ds.rst
> +* virtio seed image
It is a bit confusing, but it kinda feels beyond the scope of this article, and that's what the reference links to QEMU docs are for. The [seed image](https://cloudinit.readthedocs.io/en/latest/howto/run_cloud_init_locally.html#create-an-iso-disk) is just a disk image (iso) that contains the user data and metadata cloud-init needs to do its job. I'll add some text.

2024-08-12 17:49 UTC, k-dimple commented on public-images/public-images-how-to/use-local-cloud-init-ds.rst
> +If desired, create a YAML file with your desired datasource `metadata`_. Metadata describes typically cloud-defined
Ah now I see what you mean! Should we just remove 'typically' from the statement? It does seem like a typo on first reading!

2024-08-12 17:52 UTC, k-dimple approved these changes

2024-08-13 13:36 UTC, merged