feat(aws): add support options overview
canonical/ubuntu-cloud-docs pull request #293
Opened 2024-11-11 15:37 UTC by rpocase

This adds an overview for how to get support on AWS, including what Pro provides, AWS frontline support, and getting expanded support from Canonical

2024-11-11 17:20 UTC, rpocase commented on .custom_wordlist.txt
> +signup
is there a better way to do this? the flag seems to be on a link which i wouldn't expect to be spell checked.

2024-11-12 15:23 UTC, rpocase commented on aws/aws-reference/pro.rst
> +Ubuntu Pro on AWS
good catch on actually linking the top level page. i tend to think a briefer than the whole marketing pitch is worth while even if there is duplication. many users won't take the chance to look through the linked content unless there is enough of a blurb to get them more interested

2024-11-12 19:00 UTC, k-dimple requested changes

2024-11-12 19:00 UTC, k-dimple commented on aws/aws-reference/pro.rst
> +All Ubuntu Pro customers are entitled to usage of
```suggestion
All Ubuntu Pro customers are entitled to the usage of 
```

2024-11-12 19:00 UTC, k-dimple commented on aws/aws-reference/pro.rst
> +the `sign up page <https://landscape.canonical.com/signup>_`.
```suggestion
the `sign up page`_.

.. _`Ubuntu Pro`: https://ubuntu.com/aws/pro
.. _`ESM`: https://ubuntu.com/security/esm
.. _`Livepatch`: https://ubuntu.com/security/livepatch
.. _`Landscape`: https://ubuntu.com/landscape
.. _`sign up page`: https://landscape.canonical.com/signup
```

2024-11-12 19:00 UTC, k-dimple commented on aws/aws-reference/support.rst
> +Ubuntu Pro provides numerous support options. Please see the `Pro <pro>`_ page for
```suggestion
Ubuntu Pro provides numerous support options. Please see the :doc:`Pro <pro>` page for 
```

2024-11-12 19:00 UTC, k-dimple commented on aws/aws-reference/support.rst
> +through the `Amazon Web Services marketplace seller <https://aws.amazon.com/marketplace/search/results?searchTerms=ubuntu+pro&CREATOR=e6a5002c-6dd0-4d1e-8196-0a1d1857229b&filters=CREATOR>`_.
```suggestion
through the `Amazon Web Services marketplace <https://aws.amazon.com/marketplace/search/results?searchTerms=ubuntu+pro&CREATOR=e6a5002c-6dd0-4d1e-8196-0a1d1857229b&filters=CREATOR>`_.
```

2024-11-12 19:03 UTC, k-dimple commented
Also, could you pull the latest code from the main repo, so that the build failures on RTD can be avoided? I have pushed a small update to remove that error.

2024-11-12 19:28 UTC, rpocase commented
batch committed all of dimple's suggestions. i'll follow up tomorrow on carlos' additional comments and review the custom_wordlist to see what I can remove from before

2024-11-13 04:43 UTC, k-dimple approved these changes

2024-11-13 13:52 UTC, merged