feat(azure): Add focal to jammy upgrade doc
canonical/ubuntu-cloud-docs pull request #6
Opened 2022-08-05 18:52 UTC by AleksaSvitlica

Add documentation for Focal to Jammy upgrade on Azure. Includes pictures showing the steps which require manual input.

2022-08-05 20:01 UTC, j5awry requested changes
One general note is to keep accessibility in mind. let's make sure to add alt-text whenever we provide images. 

I'm also unsure about image paths -- should we have a separate assets folder for static assets that get shipped in?

2022-08-05 20:01 UTC, j5awry commented on docs/explanations/Azure/Focal_To_Jammy_Upgrade.md
> +![Additional SSH daemon](/docs/explanations/Azure/Focal_To_Jammy_Upgrade_Images/0_additional_ssh_daemon.png)
let's add short written descriptions under the heading, and alt-text for the images describing them

2022-08-08 07:32 UTC, gjolly commented on docs/explanations/Azure/Focal_To_Jammy_Upgrade.md
> +![Chrony modified config](/docs/explanations/Azure/Focal_To_Jammy_Upgrade_Images/4_chrony_modified_config.png)
Should we do it here or do we want to detail all the customization we do to azure images somewhere else?

2022-08-08 07:33 UTC, gjolly commented
LGTM

2022-08-10 20:58 UTC, AleksaSvitlica commented
Updated to include short descriptions for each heading and more descriptive alt-test for the images. What remains to be decided is:
- Are we okay with the image path or do we want them somewhere else?
- Do we want to provide any specific explanation about the config changes to SSHD and Chrony here or elsewhere?
- Do we have any specific advise for the UCF prompts for SSHD/Chrony? Should users keep the local configuration?

2022-08-15 19:21 UTC, j5awry approved these changes

2022-08-15 19:23 UTC, j5awry commented
> Updated to include short descriptions for each heading and more descriptive alt-test for the images. What remains to be decided is:
> 
>     * Are we okay with the image path or do we want them somewhere else?
> 
The image paths are fine. I was talking to some others about it, and, really, each screenshot ends up unique. If we choose to move later, we can.

>     * Do we want to provide any specific explanation about the config changes to SSHD and Chrony here or elsewhere?
> 
I vote elsewhere. And to make those descriptions more verbose (the "why" it's that way, and our roadmap for changes)

>     * Do we have any specific advice for the UCF prompts for SSHD/Chrony? Should users keep the local configuration?
The default it is to keep the local config. I think pointing out the difference here is enough for now. Once we build pages for the Azure specific changes, it'll help people understand more fully. Short term, if they see this, it _should_ lead users to check the configs themselves and make the decision.

2022-08-15 19:32 UTC, merged